on:
  push:
    branches: [ "main" ]

jobs:
  basic:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test secret
        env:
          MY_SECRET: ${{ secrets.TEST_SECRET }}
        run: make
